name: pg-dump
on:
  workflow_dispatch:
    branches:
      - main
jobs:
  db-backup:
    runs-on: ubuntu-latest
    steps:
      - name: Set current date as env variable
        run: echo "NOW=$(date +'%Y-%m-%dT%H:%M:%S')" >> $GITHUB_ENV
      - name: Update
        run: |
          pg_dump -V
          sudo apt-get --purge remove postgresql postgresql-*
          # Create the file repository configuration:
          sudo sh -c 'echo "deb http://apt.postgresql.org/pub/repos/apt $(lsb_release -cs)-pgdg main" > /etc/apt/sources.list.d/pgdg.list'
          # Import the repository signing key:
          wget --quiet -O - https://www.postgresql.org/media/keys/ACCC4CF8.asc | sudo apt-key add -
          # Update the package lists:
          sudo apt-get update
          # Install the latest version of PostgreSQL.
          # If you want a specific version, use 'postgresql-12' or similar instead of 'postgresql':
          sudo apt-get -y install postgresql
          pg_dump -V
      - name: Dump
        run: pg_dump -d postgres://postgres:${{ secrets.DB_PASSWORD }}@db.mmucqujjuxgcszwyrbil.supabase.co:5432/postgres -Fc > backup-$NOW.sql
      - name: Zip
        run: zip -r backup-$NOW.zip backup-$NOW.sql
      - name: 'Upload Artifact'
        uses: actions/upload-artifact@v3
        with:
          name: db-backup-$NOW
          path: backup-$NOW.zip
          retention-days: 90