name: pg-dump
on:
  workflow_dispatch:
    branches:
      - main
jobs:
  db-backup:
    runs-on: ubuntu-latest
    steps:
      - name: show pg_dump version before update
        run: pg_dump -V
      - name: download
        run: wget http://de.archive.ubuntu.com/ubuntu/pool/main/p/postgresql-15/postgresql-client-15_15.1-1_amd64.deb
      - name: install
        run: sudo dpkg -I postgresql-client-15_15.1-1_amd64.deb
      - name: show pg_dump version after update
        run: pg_dump -V
      - uses: actions/checkout@v2
      - name: Postgres Dump Backup
        uses: tj-actions/pg-dump@v2.5
        with:
          database_url: "postgres://postgres:hoduecaramelle@db.mmucqujjuxgcszwyrbil.supabase.co:5432/postgres"
          path: "backups/backup.sql" 
          options: "-O"