name: pg-dump
on:
  workflow_dispatch:
    branches:
      - main
jobs:
  db-backup:
    runs-on: ubuntu-latest
    steps:
      - name: show pg_dump version before update
        run: pg_dump -V
      - name: update
        run: sudo apt update && sudo apt upgrade
      - name: show pg_dump version after update
        run: pg_dump -V
      - uses: actions/checkout@v2
      - name: Postgres Dump Backup
        uses: tj-actions/pg-dump@v2.3
        with:
          database_url: "postgres://postgres:hoduecaramelle@db.mmucqujjuxgcszwyrbil.supabase.co:5432/postgres"
          path: "backups/backup.sql" 
          options: "-O"